name: Actions
on:
    pull_request:
    push:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - name: Python Linter
          uses: sunnysid3up/python-linter@v0.1-beta.7
          with:
              source: "src"
              mypy-options: "--ignore-missing-imports --show-error-codes"
              pylint-options: "--rcfile=setup.cfg"
              isort-options: "-w 100",
  
